server:
  port: 8761
spring:
  cloud:
    compatibility-verifier:
      enabled: false # Vô hiệu hóa kiểm tra tương thích tạm thời
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0 # Tránh chờ đồng bộ khi không có instance
    enable-self-preservation: false # Tạm thời tắt self-preservation để kiểm tra
    eviction-interval-timer-in-ms: 60000 # Đặt khoảng thời gian xóa instance không hoạt động (1 phút)
  lease:
    renewal-interval-in-seconds: 30 # Tần suất gửi heartbeat
    duration-in-seconds: 90 # Thời gian lease, nếu không gửi heartbeat sẽ bị xóa