@startuml
left to right direction

(*) --> :Thu thập dữ liệu;
--> :Tiền xử lý dữ liệu;
--> :FastText embeddings;
--> :Tạo tập dữ liệu search & test;
-down-> :Xây FAISS index;
-left-> :Đánh giá mô hình;
-left-> :Trực quan hóa kết quả;
-left-> :Triển khai & theo dõi;
-left-> (*)

@enduml
