server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/kltn_fashion_shop?useSSL=false&serverTimezone=UTC
    username: root
    password:

  mail:
    host: smtp.gmail.com
    port: 587
    username: lephuc11232@gmail.com
    password: zxkv ktdf qqng xuip
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  cloud:
    compatibility-verifier:
      enabled: false

jwt:
  secret: aGtHd1hnM3NlcEh5U3lmaDhoUWVrZ0dZN0RZbGZxVXpKbFlGbFZKZ2JPRzFqcmMybWhVZFN5N0RoT0JreEdhVg==
  expiration: 3600000
  refresh:
    expiration: 604800000

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: ${spring.application.name}:localhost:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
